/**
 * language.js
 * 多語言標籤定義（傳統格式 - 可直接在 HTML 中使用）
 */

var LANGUAGE = {
  // English
  en: {
    // Label
    label: 'English',
    // Angles
    ascendant: 'Ascendant',
    midheaven: 'Midheaven',
    // Bodies
    sun: 'Sun',
    moon: 'Moon',
    mercury: 'Mercury',
    venus: 'Venus',
    mars: 'Mars',
    jupiter: 'Jupiter',
    saturn: 'Saturn',
    uranus: 'Uranus',
    neptune: 'Neptune',
    pluto: 'Pluto',
    chiron: 'Chiron',
    sirius: 'Sirius',
    // Points
    northnode: 'North Node',
    southnode: 'South Node',
    lilith: 'Lilith',
    // Signs
    aries: 'Aries',
    taurus: 'Taurus',
    gemini: 'Gemini',
    cancer: 'Cancer',
    leo: 'Leo',
    virgo: 'Virgo',
    libra: 'Libra',
    scorpio: 'Scorpio',
    sagittarius: 'Sagittarius',
    capricorn: 'Capricorn',
    aquarius: 'Aquarius',
    pisces: 'Pisces',
    ophiuchus: 'Ophiuchus',
    // Houses
    house1: 'First',
    house2: 'Second',
    house3: 'Third',
    house4: 'Fourth',
    house5: 'Fifth',
    house6: 'Sixth',
    house7: 'Seventh',
    house8: 'Eighth',
    house9: 'Ninth',
    house10: 'Tenth',
    house11: 'Eleventh',
    house12: 'Twelfth',
    // Aspects
    conjunction: 'Conjunction',
    opposition: 'Opposition',
    trine: 'Trine',
    square: 'Square',
    sextile: 'Sextile',
    quincunx: 'Quincunx',
    quintile: 'Quintile',
    septile: 'Septile',
    'semi-square': 'Semi-Square',
    'semi-sextile': 'Semi-Sextile',
    // Zodiac Choice Labels
    'tropical-zodiac': 'Tropical',
    'sidereal-zodiac': 'Sidereal',
    // House System labels
    'equal-house': 'Equal House',
    campanus: 'Campanus',
    koch: 'Koch',
    placidus: 'Placidus',
    regiomontanus: 'Regiomontanus',
    topocentric: 'Topocentric',
    'whole-sign': 'Whole Sign',
    // Aspect level labels
    major: 'Major',
    minor: 'Minor',
    // UI Labels (新增 HTML 中需要的標籤)
    'th-ascendant': 'Ascendant',
    'th-midheaven': 'M.C. (Midheaven)',
    'th-horizon-degrees': 'Horizon Degrees',
    'th-ecliptic-degrees': 'Ecliptic Degrees',
    'th-sign-dms': 'Sign – D° M\' S"',
    'th-section-zodiac-cusps': 'Zodiac Cusps',
    'th-horizon-degrees-2': 'Horizon Degrees',
    'th-section-houses': 'Houses',
    'th-house-col': 'House',
    'th-house-start': 'Start (Ecliptic°)',
    'th-house-end': 'End (Ecliptic°)',
    'th-house-sign': 'Sign',
    'th-section-bodies': 'Celestial Bodies (Planets)',
    'th-body-name': 'Body',
    'th-body-ecl': 'Ecliptic°',
    'th-body-sign': 'Sign',
    'th-body-dms': 'D° M\' S"',
    'th-body-house': 'House',
    'th-body-retro': 'Retrograde',
    'th-section-points': 'Celestial Points',
    'th-point-name': 'Point',
    'th-point-ecl': 'Ecliptic°',
    'th-point-sign': 'Sign',
    'th-point-dms': 'D° M\' S"',
    'th-point-house': 'House',
    'th-section-aspects': 'Aspects',
    'th-asp-body1': 'Body 1',
    'th-asp-aspect': 'Aspect',
    'th-asp-body2': 'Body 2',
    'th-asp-orb': 'Orb',
    'th-asp-level': 'Level',
    'th-house-label': 'House',
    'level-major': 'Major',
    'level-minor': 'Minor',
    'no-aspects': 'No aspects found',
    // Aspect names (補充)
    northNode: 'North Node',
    southNode: 'South Node',
    semisextile: 'Semi-Sextile',
    semisquare: 'Semi-Square',
    sesquisquare: 'Sesquisquare',
    biquintile: 'Bi-Quintile'
  },
  // Spanish
  es: {
    // Label
    label: 'Español',
    // Angles
    ascendant: 'Ascendente',
    midheaven: 'Medio Cielo',
    // Bodies
    sun: 'Sol',
    moon: 'Luna',
    mercury: 'Mercurio',
    venus: 'Venus',
    mars: 'Marte',
    jupiter: 'Júpiter',
    saturn: 'Saturno',
    uranus: 'Urano',
    neptune: 'Neptuno',
    pluto: 'Plutón',
    chiron: 'Quirón',
    sirius: 'Sirio',
    // Points
    northnode: 'Nodo Norte',
    southnode: 'Nodo Sur',
    lilith: 'Lilith',
    // Signs
    aries: 'Aries',
    taurus: 'Tauro',
    gemini: 'Géminis',
    cancer: 'Cáncer',
    leo: 'Leo',
    virgo: 'Virgo',
    libra: 'Libra',
    scorpio: 'Escorpio',
    sagittarius: 'Sagitario',
    capricorn: 'Capricornio',
    aquarius: 'Acuario',
    pisces: 'Piscis',
    ophiuchus: 'Ofiuco',
    // Houses
    house1: 'Primera',
    house2: 'Segunda',
    house3: 'Tercera',
    house4: 'Cuarta',
    house5: 'Quinta',
    house6: 'Sexta',
    house7: 'Séptima',
    house8: 'Octava',
    house9: 'Novena',
    house10: 'Décima',
    house11: 'Undécima',
    house12: 'Duodécima',
    // Aspects
    conjunction: 'Conjunción',
    opposition: 'Oposición',
    trine: 'Trígono',
    square: 'Cuadrado',
    sextile: 'Sextil',
    quincunx: 'Tresbolillo',
    quintile: 'Quintil',
    septile: 'Septil',
    'semi-square': 'Semi-cuadrado',
    'semi-sextile': 'Semi-sextil',
    // Zodiac Choice Labels
    'tropical-zodiac': 'Tropical',
    'sidereal-zodiac': 'Sideral',
    // House System labels
    'equal-house': 'Casa igual',
    campanus: 'Campanus',
    koch: 'Koch',
    placidus: 'Placidus',
    regiomontanus: 'Regiomontanus',
    topocentric: 'Topocéntrico',
    'whole-sign': 'Signo Entero',
    // Aspect level labels
    major: 'Mayor',
    minor: 'Menor',
    // UI Labels
    'th-ascendant': 'Ascendente',
    'th-midheaven': 'M.C. (Medio Cielo)',
    'th-horizon-degrees': 'Grados Horizonte',
    'th-ecliptic-degrees': 'Grados Eclíptica',
    'th-sign-dms': 'Signo – G° M\' S"',
    'th-section-zodiac-cusps': 'Cúspides del Zodíaco',
    'th-horizon-degrees-2': 'Grados Horizonte',
    'th-section-houses': 'Casas',
    'th-house-col': 'Casa',
    'th-house-start': 'Inicio (Eclíptica°)',
    'th-house-end': 'Fin (Eclíptica°)',
    'th-house-sign': 'Signo',
    'th-section-bodies': 'Cuerpos Celestes (Planetas)',
    'th-body-name': 'Cuerpo',
    'th-body-ecl': 'Eclíptica°',
    'th-body-sign': 'Signo',
    'th-body-dms': 'G° M\' S"',
    'th-body-house': 'Casa',
    'th-body-retro': 'Retrógrado',
    'th-section-points': 'Puntos Celestes',
    'th-point-name': 'Punto',
    'th-point-ecl': 'Eclíptica°',
    'th-point-sign': 'Signo',
    'th-point-dms': 'G° M\' S"',
    'th-point-house': 'Casa',
    'th-section-aspects': 'Aspectos',
    'th-asp-body1': 'Cuerpo 1',
    'th-asp-aspect': 'Aspecto',
    'th-asp-body2': 'Cuerpo 2',
    'th-asp-orb': 'Orbe',
    'th-asp-level': 'Nivel',
    'th-house-label': 'Casa',
    'level-major': 'Mayor',
    'level-minor': 'Menor',
    'no-aspects': 'No se encontraron aspectos',
    // Aspect names
    northNode: 'Nodo Norte',
    southNode: 'Nodo Sur',
    semisextile: 'Semisextil',
    semisquare: 'Semicuadratura',
    sesquisquare: 'Sesquicuadratura',
    biquintile: 'Biquintil'
  },
  // Traditional Chinese
  zh: {
    // Label
    label: '繁體中文',
    // Angles
    ascendant: '上升點',
    midheaven: '天頂',
    // Bodies
    sun: '太陽',
    moon: '月亮',
    mercury: '水星',
    venus: '金星',
    mars: '火星',
    jupiter: '木星',
    saturn: '土星',
    uranus: '天王星',
    neptune: '海王星',
    pluto: '冥王星',
    chiron: '凱龍星',
    sirius: '天狼星',
    // Points
    northnode: '北交點',
    southnode: '南交點',
    lilith: '莉莉絲',
    // Signs
    aries: '牡羊座',
    taurus: '金牛座',
    gemini: '雙子座',
    cancer: '巨蟹座',
    leo: '獅子座',
    virgo: '處女座',
    libra: '天秤座',
    scorpio: '天蠍座',
    sagittarius: '射手座',
    capricorn: '摩羯座',
    aquarius: '水瓶座',
    pisces: '雙魚座',
    ophiuchus: '蛇夫座',
    // Houses
    house1: '第一宮',
    house2: '第二宮',
    house3: '第三宮',
    house4: '第四宮',
    house5: '第五宮',
    house6: '第六宮',
    house7: '第七宮',
    house8: '第八宮',
    house9: '第九宮',
    house10: '第十宮',
    house11: '第十一宮',
    house12: '第十二宮',
    // Aspects
    conjunction: '合相',
    opposition: '對分相',
    trine: '三分相',
    square: '四分相',
    sextile: '六分相',
    quincunx: '十二分之五相',
    quintile: '五分相',
    septile: '七分相',
    'semi-square': '八分相',
    'semi-sextile': '十二分相',
    // Zodiac Choice Labels
    'tropical-zodiac': '回歸黃道',
    'sidereal-zodiac': '恆星黃道',
    // House System labels
    'equal-house': '等宮制',
    campanus: '坎帕努斯制',
    koch: '科赫制',
    placidus: '普拉西德斯制',
    regiomontanus: '雷吉蒙塔努斯制',
    topocentric: '地心制',
    'whole-sign': '整個星座制',
    // Aspect level labels
    major: '主要',
    minor: '次要',
    // UI Labels
    'th-ascendant': '上升點',
    'th-midheaven': '天頂（M.C.）',
    'th-horizon-degrees': '地平度數',
    'th-ecliptic-degrees': '黃道度數',
    'th-sign-dms': '星座 – 度° 分\' 秒"',
    'th-section-zodiac-cusps': '黃道宮頭',
    'th-horizon-degrees-2': '地平度數',
    'th-section-houses': '宮位',
    'th-house-col': '宮位',
    'th-house-start': '起始（黃道°）',
    'th-house-end': '結束（黃道°）',
    'th-house-sign': '星座',
    'th-section-bodies': '天體（行星）',
    'th-body-name': '天體',
    'th-body-ecl': '黃道°',
    'th-body-sign': '星座',
    'th-body-dms': '度° 分\' 秒"',
    'th-body-house': '宮位',
    'th-body-retro': '逆行',
    'th-section-points': '特殊點',
    'th-point-name': '特殊點',
    'th-point-ecl': '黃道°',
    'th-point-sign': '星座',
    'th-point-dms': '度° 分\' 秒"',
    'th-point-house': '宮位',
    'th-section-aspects': '相位',
    'th-asp-body1': '天體 1',
    'th-asp-aspect': '相位',
    'th-asp-body2': '天體 2',
    'th-asp-orb': '容許度',
    'th-asp-level': '等級',
    'th-house-label': '宮',
    'level-major': '主要',
    'level-minor': '次要',
    'no-aspects': '未找到相位',
    // Aspect names
    northNode: '北交點',
    southNode: '南交點',
    semisextile: '十二分相',
    semisquare: '八分相',
    sesquisquare: '倍八分相',
    biquintile: '雙五分相'
  }
};